// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm7FkwRVmq-wpsS3pZA5FW6vk4x4xXTQU',
    appId: '1:368015209080:web:94f6c35e613bac9da9b38d',
    messagingSenderId: '368015209080',
    projectId: 'varietesinuds',
    authDomain: 'varietesinuds.firebaseapp.com',
    databaseURL: 'https://varietesinuds-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'varietesinuds.appspot.com',
    measurementId: 'G-NT2WWKEGT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCho5UxehCKNKismhYfctB8EQRnuRZtQ8Q',
    appId: '1:368015209080:android:09fe6c194ead583fa9b38d',
    messagingSenderId: '368015209080',
    projectId: 'varietesinuds',
    databaseURL: 'https://varietesinuds-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'varietesinuds.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjtVnNZuuCvGAmU1Enpc98qfxHsEtzV_I',
    appId: '1:368015209080:ios:de9eba7a89d287dca9b38d',
    messagingSenderId: '368015209080',
    projectId: 'varietesinuds',
    databaseURL: 'https://varietesinuds-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'varietesinuds.appspot.com',
    iosBundleId: 'com.example.viLight',
  );

}